### ISSUE TITLE
[PROBLEM] ExtractText() Behaviour differences in new version( 3.0.3 to 3.14.0)

### ISSUE THREAD

**Issue by cyberlord29** [unidoc/unipdf#427] opened 2020-11-25 09:15 UTC
## Description
We have migrated from v 3.0.3 to 3.14.0 to get the table extraction features.

The extractText function behaviour has changed when the line is part of a table, it seems to parse each cell row by row and then move to the next column , instead of just spitting out the whole row as it did in the previous versions.

Please let me know if you are able to recognize this issue , I can add detailed screenshots etc if you aren't.

Thanks a lot.

**Comment by gunnsth** [comment] 2020-11-25 10:08
@cyberlord29 Can you define the problem and provide the actual files where the regression can be clearly seen.  As such it is not unexpected that the output can change, as long as the quality, in terms of visual comparison is getting better.

**Comment by cyberlord29** [comment] 2020-11-25 11:55
@gunnsth  So here is the PDF Screenshot , 

<img width="1032" alt="Screenshot 2020-11-25 at 17 11 19" src="https://user-images.githubusercontent.com/19804038/100224338-b7077b80-2f42-11eb-84f4-b24f8936b882.png">

Here is the output of extractText() of versions v3.0.3 - v3.8.0

<img width="1023" alt="Screenshot 2020-11-25 at 17 13 02" src="https://user-images.githubusercontent.com/19804038/100224440-d6060d80-2f42-11eb-93fc-7285cbb20143.png">

Here is the output of extractText() of versions v3.9.0 + 

<img width="760" alt="Screenshot 2020-11-25 at 17 10 42" src="https://user-images.githubusercontent.com/19804038/100224511-ef0ebe80-2f42-11eb-9b96-e4dcc6221460.png">

Can we still utilize the legacy behaviour in the newer packages ? 

Tables is not an option here as PageText.Tables() is not able to properly parse the table as there are some sparse rows in between, (will add screenshots for those shortly).

Thanks.

**Comment by gunnsth** [comment] 2020-11-25 12:00
Thanks, that makes sense, we will look into this and get back to you.  Might make sense to have some options here as for some cases the tables make sense whereas others not.

**Comment by cyberlord29** [comment] 2020-11-25 12:21
@gunnsth yeah thanks , Please let us know , as we are deciding on a license renewal as well.

**Comment by cyberlord29** [comment] 2020-11-25 12:26
@gunnsth also please let us know if there is any dirty fix to get this behaviour 😅  , Thanks.

**Comment by peterwilliams97** [comment] 2020-11-25 21:47
Hi @cyberlord29 
It looks like my table extraction code changes caused this problem. Those changes improve extraction of many other types of tables. We can give you a better experience by fixing those changes to work with your table than by reverting the changes,
Are you able to share the PDF file that contains the table with us?

**Comment by cyberlord29** [comment] 2020-11-25 22:39
@peterwilliams97 That sounds great , can you leave an email Id here so I can send it to you ?

**Comment by peterwilliams97** [comment] 2020-11-30 21:31
peter.wi

> @peterwilliams97 That sounds great , can you leave an email Id here so I can send it to you ?

peter.williams.97@gmail.com

**Comment by peterwilliams97** [comment] 2021-01-11 11:16
Hi Maneesh

Sorry for the late reply. This is my email.

----------------------------------------------
Peter Williams
0488 783 700 / +61 488 783 700

**Comment by anovik** [comment] 2024-12-02 06:46
@cyberlord29 Recently we have released https://github.com/unidoc/unipdf/releases/tag/v3.64.0 and currently both behaviors are supported. 

The default one includes table detection but if you don't need it you just enable simple mode (https://github.com/unidoc/unipdf-examples/blob/master/extract/pdf_simple_extraction.go see this example for details) and then you get row by row extraction. 

I am closing this issue, feel free to open another ticket in case of any problem. Thanks!

**Closed by anovik** 2024-12-02 06:46 UTC
