### ISSUE TITLE
[BUG] Problem with Chinese when creating table of contents in creator package

### ISSUE THREAD

**Issue by lorddang** [unidoc/unipdf#193] opened 2019-10-23 10:02 UTC
**Is your feature request related to a problem? Please describe.**
Not support chinese when create pdf

**Comment by gunnsth** [comment] 2019-10-23 18:57
@lorddang Please see https://github.com/unidoc/unipdf/issues/87#issuecomment-529105921
and https://github.com/unidoc/unipdf/blob/76a1225d32f4ea5881b3f643b82ff11c91cc525f/creator/creator_test.go#L675

**Comment by lorddang** [comment] 2019-10-24 04:17
thanks u, it works, but when I generate the table of contents use option c.AddTOC = true, it didn't work, the chinese charact didn't show in the toc line, when I use toc.AddLine() method add toc line , the chinese charact can show, I am sure font is right. is it bug ? thank u

**Comment by day-dreams** [comment] 2019-11-24 16:50
> thanks u, it works, but when I generate the table of contents use option c.AddTOC = true, it didn't work, the chinese charact didn't show in the toc line, when I use toc.AddLine() method add toc line , the chinese charact can show, I am sure font is right. is it bug ? thank u @gunnsth

i meet the same issue.
problem seems to be here, in creator/toc.go, line 116:
```golang
         tl := t.AddLine(newStyledTOCLine(
		TextChunk{
			Text:  number,
			Style: t.lineNumberStyle,
		},
		TextChunk{
			Text:  title,
			Style: t.lineTitleStyle,
		},
		TextChunk{
			Text:  page,
			Style: t.linePageStyle,
		},
		level,
		t.defaultStyle, //  line 116
	))
```
it  uses creator.defaultFontRegular to create TocLine, instead of user's custom font. 
the font encoder of creator.defaultFontRegular , which is simpleEncoding(WinAnsiEncoding), can not handle chinese correctly. 

my solution is use t.lineTitleStyle ( instead of t.defaultStyle ) to create TocLine,  as below:
```golang
	tl := t.AddLine(newStyledTOCLine(
		TextChunk{
			Text:  number,
			Style: t.lineNumberStyle,
		},
		TextChunk{
			Text:  title,
			Style: t.lineTitleStyle,
		},
		TextChunk{
			Text:  page,
			Style: t.linePageStyle,
		},
		level,
		t.lineTitleStyle, // use t.lineTitleStyle, instead of t.defaultStyle
	))
```
hoping this can help you @lorddang 
also, hoping this can be fixed. thks @gunnsth

**Comment by gunnsth** [comment] 2019-11-25 18:53
@lorddang Can you provide a self-contained example so we can reproduce this and verify that it has been fixed once we have addressed it?

@day-dreams Thanks for the analysis.

**Comment by adrg** [comment] 2019-11-26 22:03
@lorddang @day-dreams. There was indeed a bug with the TOC component. The issue was that the TOC line link styles were overwriting previous style changes of the TOC line component (like the font set by the user). The issue does not reproduce when automatic link generation is disabled.

I added a basic example of how to create a table of contents automatically, from chapters with Chinese headings. Granted, I'm not sure what the headings say exactly, I copied them from the test I referenced in the sample.

The solution works if you run it against the latest commit of the development branch. If that's not a possibility, I added a comment in the sample which points to another solution to the issue, by using the `CreateTableOfContents` method of the creator.

```
package main

import (
	"log"

	"github.com/unidoc/unipdf/creator"
	"github.com/unidoc/unipdf/model"
)

func main() {
	c := creator.New()
	c.AddTOC = true

	// Load composite font.
	font, err := model.NewCompositePdfFontFromTTFFile("/path/to/unipdf/creator/testdata/wts11.ttf")
	if err != nil {
		log.Fatal(err)
	}

	// Set line title style before drawing chapters, or other components
	// which generate TOC lines, as the new style only affects new TOC lines.
	lineTitleStyle := c.NewTextStyle()
	lineTitleStyle.Font = font

	toc := c.TOC()
	toc.SetLineTitleStyle(lineTitleStyle)
	// The other option is to use the CreateTableOfContents method of the
	// creator modify the styles of the lines, just before document write, in
	// the callback:
	// https://github.com/unidoc/unipdf/blob/development/creator/creator_test.go#L892

	// Draw first chapter.
	chap1 := c.NewChapter("你好你好你好你好")
	chap1.GetHeading().SetFont(font)

	if err := c.Draw(chap1); err != nil {
		log.Fatal(err)
	}

	// Draw second chapter.
	chap2 := c.NewChapter("河上白云")
	chap2.GetHeading().SetFont(font)

	if err := c.Draw(chap2); err != nil {
		log.Fatal(err)
	}

	// Write document.
	if err := c.WriteToFile("out.pdf"); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by gunnsth** [comment] 2019-12-14 17:45
@lorddang @day-dreams  Can you confirm that it works now?

**Comment by lorddang** [comment] 2019-12-15 03:27
@gunnsth @adrg  thank u very much , it table of content looks well, but  the outline of pdf not works.

![image](https://user-images.githubusercontent.com/21157317/70857646-8e52c580-1f2d-11ea-9900-3c02f06e6bbe.png)

maybe it same reason.

**Comment by gunnsth** [comment] 2020-01-13 22:07
@lorddang Can you check and verify that PR #223 resolves the problem?  Then we should be able to close this issue.

**Comment by lorddang** [comment] 2020-01-18 06:45
@gunnsth  The problem has been fixed. thank u very much.

**Closed** 2020-01-18 11:00 UTC
Labels: bug
